name: Deploy to StaticDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build static bundle
        run: npm run build
      
      - name: Install StaticDeploy CLI
        run: npm install -g @staticdeploy/cli
      
      - name: Deploy to StaticDeploy
        run: |
          export STATICDEPLOY_API_URL="https://public.ka-ve.io/api"
          export STATICDEPLOY_API_TOKEN="${{ secrets.STATICDEPLOY_API_TOKEN }}"
          npm run deploy 